/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IMessageData,
} from './classes/MessageData';
import {
  IMotorDebuggerData,
} from './classes/MotorData';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CardObject {
    'title': string;
  }
  interface CardObjectAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface DataItem {
    'title': string;
  }
  interface DataItemAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface MessagesComponent {
    'data': IMessageData[];
  }
  interface MessagesComponentAttributes extends StencilHTMLAttributes {
    'data'?: IMessageData[];
  }

  interface MotorComponent {
    'data': IMotorDebuggerData;
  }
  interface MotorComponentAttributes extends StencilHTMLAttributes {
    'data'?: IMotorDebuggerData;
  }

  interface ValueUnitDisplay {
    'unit': string;
    'value': any;
  }
  interface ValueUnitDisplayAttributes extends StencilHTMLAttributes {
    'unit'?: string;
    'value'?: any;
  }

  interface XComponent {}
  interface XComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'CardObject': Components.CardObject;
    'DataItem': Components.DataItem;
    'MessagesComponent': Components.MessagesComponent;
    'MotorComponent': Components.MotorComponent;
    'ValueUnitDisplay': Components.ValueUnitDisplay;
    'XComponent': Components.XComponent;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'card-object': Components.CardObjectAttributes;
    'data-item': Components.DataItemAttributes;
    'messages-component': Components.MessagesComponentAttributes;
    'motor-component': Components.MotorComponentAttributes;
    'value-unit-display': Components.ValueUnitDisplayAttributes;
    'x-component': Components.XComponentAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCardObjectElement extends Components.CardObject, HTMLStencilElement {}
  var HTMLCardObjectElement: {
    prototype: HTMLCardObjectElement;
    new (): HTMLCardObjectElement;
  };

  interface HTMLDataItemElement extends Components.DataItem, HTMLStencilElement {}
  var HTMLDataItemElement: {
    prototype: HTMLDataItemElement;
    new (): HTMLDataItemElement;
  };

  interface HTMLMessagesComponentElement extends Components.MessagesComponent, HTMLStencilElement {}
  var HTMLMessagesComponentElement: {
    prototype: HTMLMessagesComponentElement;
    new (): HTMLMessagesComponentElement;
  };

  interface HTMLMotorComponentElement extends Components.MotorComponent, HTMLStencilElement {}
  var HTMLMotorComponentElement: {
    prototype: HTMLMotorComponentElement;
    new (): HTMLMotorComponentElement;
  };

  interface HTMLValueUnitDisplayElement extends Components.ValueUnitDisplay, HTMLStencilElement {}
  var HTMLValueUnitDisplayElement: {
    prototype: HTMLValueUnitDisplayElement;
    new (): HTMLValueUnitDisplayElement;
  };

  interface HTMLXComponentElement extends Components.XComponent, HTMLStencilElement {}
  var HTMLXComponentElement: {
    prototype: HTMLXComponentElement;
    new (): HTMLXComponentElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'card-object': HTMLCardObjectElement
    'data-item': HTMLDataItemElement
    'messages-component': HTMLMessagesComponentElement
    'motor-component': HTMLMotorComponentElement
    'value-unit-display': HTMLValueUnitDisplayElement
    'x-component': HTMLXComponentElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'card-object': HTMLCardObjectElement;
    'data-item': HTMLDataItemElement;
    'messages-component': HTMLMessagesComponentElement;
    'motor-component': HTMLMotorComponentElement;
    'value-unit-display': HTMLValueUnitDisplayElement;
    'x-component': HTMLXComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
